# -*- coding: utf-8 -*-
"""sales analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X5tHJ8Lrq0jh4jN-yQJJyWrFYQzm9vCT
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

df = pd.read_excel("sales_data_with_missing.xlsx")
df.head(100)

print(df.describe(include='all'))

# Fill missing categorical values
df['Region'].fillna('Unknown', inplace=True)
df['Product'].fillna('Unknown', inplace=True)
df['Sales Rep'].fillna('Unassigned', inplace=True)

# Fill missing numerical values
df['Units Sold'].fillna(0, inplace=True)
df['Unit Price'].fillna(df['Unit Price'].mean(), inplace=True)

# Recalculate Total Revenue
df['Total Revenue'] = df['Units Sold'] * df['Unit Price']

# Convert Date column
df['Date'] = pd.to_datetime(df['Date'])
df.head(100)

# Revenue by Region
region_rev = df.groupby("Region")["Total Revenue"].sum().sort_values(ascending=False)
plt.figure(figsize=(8, 4))
region_rev.plot(kind='bar', color='skyblue')
plt.title("Total Revenue by Region")
plt.ylabel("Revenue")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Top Sales Reps
rep_perf = df.groupby("Sales Rep")["Total Revenue"].sum().sort_values(ascending=False).head(5)
plt.figure(figsize=(8, 4))
rep_perf.plot(kind='bar', color='orchid')
plt.title("Top 5 Sales Reps by Revenue")
plt.ylabel("Revenue")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()